import { Theme } from '@material-ui/core/styles';

export const styles = (theme: Theme) => ({
  snackbar: {
    width: '408px',
    maxWidth: 'calc(100% - 16px)',
    maxHeight: 'calc(100% - 16px)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'column' as const,
  },
  snackbarContainer: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
  },
  topBar: {
    height: '10px',
    borderRadius: '4px 4px 0 0',
    backgroundColor: theme.palette.background.snackbars.bgLine,
    flexShrink: 0,
    flexGrow: 0,
  },
  progressBar25: {
    width: '25%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
    transitionTimingFunction: 'ease-in',
    transition: '0.3s',
  },
  progressBar50: {
    width: '50%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
    transitionTimingFunction: 'ease-in',
    transition: '0.3s',
  },
  progressBar75: {
    width: '75%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
    transitionTimingFunction: 'ease-in',
    transition: '0.3s',
  },
  successBar: {
    width: '100%',
    margin: 0,
    height: '100%',
    backgroundColor: theme.palette.primary.main,
    borderRadius: '4px 4px 0 0',
    transitionTimingFunction: 'ease-in',
    transition: '0.3s',
  },
  errorBar: {
    width: '100%',
    margin: 0,
    height: '100%',
    backgroundColor: theme.palette.background.snackbars.error,
    borderRadius: '4px 4px 0 0',
    transitionTimingFunction: 'ease-in',
    transition: '0.3s',
  },
  titleContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexShrink: 0,
    marginBottom: '4px',
  },
  closeIcon: {
    padding: 0,
  },
  contentContainer: {
    backgroundColor: theme.palette.background.snackbars.bg,
    borderRadius: '0 0 4px 4px',
    padding: '12px 16px',
    minHeight: 0,
    flexShrink: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'auto',
  },
  closeBtn: {
    marginTop: theme.spacing(3),
  },
  redirectLinkSuccess: {
    color: theme.palette.primary.main,
    background: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    textDecoration: 'none',
    marginTop: '16px',
    '& .MuiSvgIcon-root': {
      marginLeft: '4px',
    },
  },
  statusContainer: {
    display: 'flex',
    justifyContent: 'space-between',
  },
});
