export declare const SelectArrow: import("@repo/styles/jsx").StyledComponent<import("react").ElementType, {
    string?: number | string | undefined | undefined;
    type?: string | undefined | undefined;
    id?: string | undefined | undefined;
    name?: string | undefined | undefined;
    mode?: number | string | undefined | undefined;
    active?: boolean | undefined;
    ref?: import("react").LegacyRef<SVGSVGElement> | undefined;
    key?: import("react").Key | null | undefined;
    suppressHydrationWarning?: boolean | undefined | undefined;
    className?: string | undefined | undefined;
    color?: string | undefined | undefined;
    height?: number | string | undefined | undefined;
    lang?: string | undefined | undefined;
    max?: number | string | undefined | undefined;
    media?: string | undefined | undefined;
    method?: string | undefined | undefined;
    min?: number | string | undefined | undefined;
    style?: import("react").CSSProperties | undefined;
    target?: string | undefined | undefined;
    width?: number | string | undefined | undefined;
    role?: import("react").AriaRole | undefined;
    tabIndex?: number | undefined | undefined;
    crossOrigin?: "" | "anonymous" | "use-credentials" | undefined;
    accentHeight?: number | string | undefined | undefined;
    accumulate?: "none" | "sum" | undefined | undefined;
    additive?: "replace" | "sum" | undefined | undefined;
    alignmentBaseline?: "auto" | "baseline" | "before-edge" | "text-before-edge" | "middle" | "central" | "after-edge" | "text-after-edge" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "inherit" | undefined | undefined;
    allowReorder?: "no" | "yes" | undefined | undefined;
    alphabetic?: number | string | undefined | undefined;
    amplitude?: number | string | undefined | undefined;
    arabicForm?: "initial" | "medial" | "terminal" | "isolated" | undefined | undefined;
    ascent?: number | string | undefined | undefined;
    attributeName?: string | undefined | undefined;
    attributeType?: string | undefined | undefined;
    autoReverse?: (boolean | "true" | "false") | undefined;
    azimuth?: number | string | undefined | undefined;
    baseFrequency?: number | string | undefined | undefined;
    baselineShift?: number | string | undefined | undefined;
    baseProfile?: number | string | undefined | undefined;
    bbox?: number | string | undefined | undefined;
    begin?: number | string | undefined | undefined;
    bias?: number | string | undefined | undefined;
    by?: number | string | undefined | undefined;
    calcMode?: number | string | undefined | undefined;
    capHeight?: number | string | undefined | undefined;
    clip?: number | string | undefined | undefined;
    clipPath?: string | undefined | undefined;
    clipPathUnits?: number | string | undefined | undefined;
    clipRule?: number | string | undefined | undefined;
    colorInterpolation?: number | string | undefined | undefined;
    colorInterpolationFilters?: "auto" | "sRGB" | "linearRGB" | "inherit" | undefined | undefined;
    colorProfile?: number | string | undefined | undefined;
    colorRendering?: number | string | undefined | undefined;
    contentScriptType?: number | string | undefined | undefined;
    contentStyleType?: number | string | undefined | undefined;
    cursor?: number | string | undefined | undefined;
    cx?: number | string | undefined | undefined;
    cy?: number | string | undefined | undefined;
    d?: string | undefined | undefined;
    decelerate?: number | string | undefined | undefined;
    descent?: number | string | undefined | undefined;
    diffuseConstant?: number | string | undefined | undefined;
    direction?: number | string | undefined | undefined;
    display?: number | string | undefined | undefined;
    divisor?: number | string | undefined | undefined;
    dominantBaseline?: "auto" | "use-script" | "no-change" | "reset-size" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "central" | "middle" | "text-after-edge" | "text-before-edge" | "inherit" | undefined | undefined;
    dur?: number | string | undefined | undefined;
    dx?: number | string | undefined | undefined;
    dy?: number | string | undefined | undefined;
    edgeMode?: number | string | undefined | undefined;
    elevation?: number | string | undefined | undefined;
    enableBackground?: number | string | undefined | undefined;
    end?: number | string | undefined | undefined;
    exponent?: number | string | undefined | undefined;
    externalResourcesRequired?: (boolean | "true" | "false") | undefined;
    fill?: string | undefined | undefined;
    fillOpacity?: number | string | undefined | undefined;
    fillRule?: "nonzero" | "evenodd" | "inherit" | undefined | undefined;
    filter?: string | undefined | undefined;
    filterRes?: number | string | undefined | undefined;
    filterUnits?: number | string | undefined | undefined;
    floodColor?: number | string | undefined | undefined;
    floodOpacity?: number | string | undefined | undefined;
    focusable?: "auto" | (boolean | "true" | "false") | undefined;
    fontFamily?: string | undefined | undefined;
    fontSize?: number | string | undefined | undefined;
    fontSizeAdjust?: number | string | undefined | undefined;
    fontStretch?: number | string | undefined | undefined;
    fontStyle?: number | string | undefined | undefined;
    fontVariant?: number | string | undefined | undefined;
    fontWeight?: number | string | undefined | undefined;
    format?: number | string | undefined | undefined;
    fr?: number | string | undefined | undefined;
    from?: number | string | undefined | undefined;
    fx?: number | string | undefined | undefined;
    fy?: number | string | undefined | undefined;
    g1?: number | string | undefined | undefined;
    g2?: number | string | undefined | undefined;
    glyphName?: number | string | undefined | undefined;
    glyphOrientationHorizontal?: number | string | undefined | undefined;
    glyphOrientationVertical?: number | string | undefined | undefined;
    glyphRef?: number | string | undefined | undefined;
    gradientTransform?: string | undefined | undefined;
    gradientUnits?: string | undefined | undefined;
    hanging?: number | string | undefined | undefined;
    horizAdvX?: number | string | undefined | undefined;
    horizOriginX?: number | string | undefined | undefined;
    href?: string | undefined | undefined;
    ideographic?: number | string | undefined | undefined;
    imageRendering?: number | string | undefined | undefined;
    in2?: number | string | undefined | undefined;
    in?: string | undefined | undefined;
    intercept?: number | string | undefined | undefined;
    k1?: number | string | undefined | undefined;
    k2?: number | string | undefined | undefined;
    k3?: number | string | undefined | undefined;
    k4?: number | string | undefined | undefined;
    k?: number | string | undefined | undefined;
    kernelMatrix?: number | string | undefined | undefined;
    kernelUnitLength?: number | string | undefined | undefined;
    kerning?: number | string | undefined | undefined;
    keyPoints?: number | string | undefined | undefined;
    keySplines?: number | string | undefined | undefined;
    keyTimes?: number | string | undefined | undefined;
    lengthAdjust?: number | string | undefined | undefined;
    letterSpacing?: number | string | undefined | undefined;
    lightingColor?: number | string | undefined | undefined;
    limitingConeAngle?: number | string | undefined | undefined;
    local?: number | string | undefined | undefined;
    markerEnd?: string | undefined | undefined;
    markerHeight?: number | string | undefined | undefined;
    markerMid?: string | undefined | undefined;
    markerStart?: string | undefined | undefined;
    markerUnits?: number | string | undefined | undefined;
    markerWidth?: number | string | undefined | undefined;
    mask?: string | undefined | undefined;
    maskContentUnits?: number | string | undefined | undefined;
    maskUnits?: number | string | undefined | undefined;
    mathematical?: number | string | undefined | undefined;
    numOctaves?: number | string | undefined | undefined;
    offset?: number | string | undefined | undefined;
    opacity?: number | string | undefined | undefined;
    operator?: number | string | undefined | undefined;
    order?: number | string | undefined | undefined;
    orient?: number | string | undefined | undefined;
    orientation?: number | string | undefined | undefined;
    origin?: number | string | undefined | undefined;
    overflow?: number | string | undefined | undefined;
    overlinePosition?: number | string | undefined | undefined;
    overlineThickness?: number | string | undefined | undefined;
    paintOrder?: number | string | undefined | undefined;
    panose1?: number | string | undefined | undefined;
    path?: string | undefined | undefined;
    pathLength?: number | string | undefined | undefined;
    patternContentUnits?: string | undefined | undefined;
    patternTransform?: number | string | undefined | undefined;
    patternUnits?: string | undefined | undefined;
    pointerEvents?: number | string | undefined | undefined;
    points?: string | undefined | undefined;
    pointsAtX?: number | string | undefined | undefined;
    pointsAtY?: number | string | undefined | undefined;
    pointsAtZ?: number | string | undefined | undefined;
    preserveAlpha?: (boolean | "true" | "false") | undefined;
    preserveAspectRatio?: string | undefined | undefined;
    primitiveUnits?: number | string | undefined | undefined;
    r?: number | string | undefined | undefined;
    radius?: number | string | undefined | undefined;
    refX?: number | string | undefined | undefined;
    refY?: number | string | undefined | undefined;
    renderingIntent?: number | string | undefined | undefined;
    repeatCount?: number | string | undefined | undefined;
    repeatDur?: number | string | undefined | undefined;
    requiredExtensions?: number | string | undefined | undefined;
    requiredFeatures?: number | string | undefined | undefined;
    restart?: number | string | undefined | undefined;
    result?: string | undefined | undefined;
    rotate?: number | string | undefined | undefined;
    rx?: number | string | undefined | undefined;
    ry?: number | string | undefined | undefined;
    scale?: number | string | undefined | undefined;
    seed?: number | string | undefined | undefined;
    shapeRendering?: number | string | undefined | undefined;
    slope?: number | string | undefined | undefined;
    spacing?: number | string | undefined | undefined;
    specularConstant?: number | string | undefined | undefined;
    specularExponent?: number | string | undefined | undefined;
    speed?: number | string | undefined | undefined;
    spreadMethod?: string | undefined | undefined;
    startOffset?: number | string | undefined | undefined;
    stdDeviation?: number | string | undefined | undefined;
    stemh?: number | string | undefined | undefined;
    stemv?: number | string | undefined | undefined;
    stitchTiles?: number | string | undefined | undefined;
    stopColor?: string | undefined | undefined;
    stopOpacity?: number | string | undefined | undefined;
    strikethroughPosition?: number | string | undefined | undefined;
    strikethroughThickness?: number | string | undefined | undefined;
    stroke?: string | undefined | undefined;
    strokeDasharray?: string | number | undefined | undefined;
    strokeDashoffset?: string | number | undefined | undefined;
    strokeLinecap?: "butt" | "round" | "square" | "inherit" | undefined | undefined;
    strokeLinejoin?: "miter" | "round" | "bevel" | "inherit" | undefined | undefined;
    strokeMiterlimit?: number | string | undefined | undefined;
    strokeOpacity?: number | string | undefined | undefined;
    strokeWidth?: number | string | undefined | undefined;
    surfaceScale?: number | string | undefined | undefined;
    systemLanguage?: number | string | undefined | undefined;
    tableValues?: number | string | undefined | undefined;
    targetX?: number | string | undefined | undefined;
    targetY?: number | string | undefined | undefined;
    textAnchor?: "start" | "middle" | "end" | "inherit" | undefined | undefined;
    textDecoration?: number | string | undefined | undefined;
    textLength?: number | string | undefined | undefined;
    textRendering?: number | string | undefined | undefined;
    to?: number | string | undefined | undefined;
    transform?: string | undefined | undefined;
    transformOrigin?: string | undefined | undefined;
    u1?: number | string | undefined | undefined;
    u2?: number | string | undefined | undefined;
    underlinePosition?: number | string | undefined | undefined;
    underlineThickness?: number | string | undefined | undefined;
    unicode?: number | string | undefined | undefined;
    unicodeBidi?: number | string | undefined | undefined;
    unicodeRange?: number | string | undefined | undefined;
    unitsPerEm?: number | string | undefined | undefined;
    vAlphabetic?: number | string | undefined | undefined;
    values?: string | undefined | undefined;
    vectorEffect?: number | string | undefined | undefined;
    version?: string | undefined | undefined;
    vertAdvY?: number | string | undefined | undefined;
    vertOriginX?: number | string | undefined | undefined;
    vertOriginY?: number | string | undefined | undefined;
    vHanging?: number | string | undefined | undefined;
    vIdeographic?: number | string | undefined | undefined;
    viewBox?: string | undefined | undefined;
    viewTarget?: number | string | undefined | undefined;
    visibility?: number | string | undefined | undefined;
    vMathematical?: number | string | undefined | undefined;
    widths?: number | string | undefined | undefined;
    wordSpacing?: number | string | undefined | undefined;
    writingMode?: number | string | undefined | undefined;
    x1?: number | string | undefined | undefined;
    x2?: number | string | undefined | undefined;
    x?: number | string | undefined | undefined;
    xChannelSelector?: string | undefined | undefined;
    xHeight?: number | string | undefined | undefined;
    xlinkActuate?: string | undefined | undefined;
    xlinkArcrole?: string | undefined | undefined;
    xlinkHref?: string | undefined | undefined;
    xlinkRole?: string | undefined | undefined;
    xlinkShow?: string | undefined | undefined;
    xlinkTitle?: string | undefined | undefined;
    xlinkType?: string | undefined | undefined;
    xmlBase?: string | undefined | undefined;
    xmlLang?: string | undefined | undefined;
    xmlns?: string | undefined | undefined;
    xmlnsXlink?: string | undefined | undefined;
    xmlSpace?: string | undefined | undefined;
    y1?: number | string | undefined | undefined;
    y2?: number | string | undefined | undefined;
    y?: number | string | undefined | undefined;
    yChannelSelector?: string | undefined | undefined;
    z?: number | string | undefined | undefined;
    zoomAndPan?: string | undefined | undefined;
    "aria-activedescendant"?: string | undefined | undefined;
    "aria-atomic"?: (boolean | "true" | "false") | undefined;
    "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined | undefined;
    "aria-braillelabel"?: string | undefined | undefined;
    "aria-brailleroledescription"?: string | undefined | undefined;
    "aria-busy"?: (boolean | "true" | "false") | undefined;
    "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
    "aria-colcount"?: number | undefined | undefined;
    "aria-colindex"?: number | undefined | undefined;
    "aria-colindextext"?: string | undefined | undefined;
    "aria-colspan"?: number | undefined | undefined;
    "aria-controls"?: string | undefined | undefined;
    "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined | undefined;
    "aria-describedby"?: string | undefined | undefined;
    "aria-description"?: string | undefined | undefined;
    "aria-details"?: string | undefined | undefined;
    "aria-disabled"?: (boolean | "true" | "false") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined | undefined;
    "aria-errormessage"?: string | undefined | undefined;
    "aria-expanded"?: (boolean | "true" | "false") | undefined;
    "aria-flowto"?: string | undefined | undefined;
    "aria-grabbed"?: (boolean | "true" | "false") | undefined;
    "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined | undefined;
    "aria-hidden"?: (boolean | "true" | "false") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined | undefined;
    "aria-keyshortcuts"?: string | undefined | undefined;
    "aria-label"?: string | undefined | undefined;
    "aria-labelledby"?: string | undefined | undefined;
    "aria-level"?: number | undefined | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined | undefined;
    "aria-modal"?: (boolean | "true" | "false") | undefined;
    "aria-multiline"?: (boolean | "true" | "false") | undefined;
    "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined | undefined;
    "aria-owns"?: string | undefined | undefined;
    "aria-placeholder"?: string | undefined | undefined;
    "aria-posinset"?: number | undefined | undefined;
    "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
    "aria-readonly"?: (boolean | "true" | "false") | undefined;
    "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined | undefined;
    "aria-required"?: (boolean | "true" | "false") | undefined;
    "aria-roledescription"?: string | undefined | undefined;
    "aria-rowcount"?: number | undefined | undefined;
    "aria-rowindex"?: number | undefined | undefined;
    "aria-rowindextext"?: string | undefined | undefined;
    "aria-rowspan"?: number | undefined | undefined;
    "aria-selected"?: (boolean | "true" | "false") | undefined;
    "aria-setsize"?: number | undefined | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined | undefined;
    "aria-valuemax"?: number | undefined | undefined;
    "aria-valuemin"?: number | undefined | undefined;
    "aria-valuenow"?: number | undefined | undefined;
    "aria-valuetext"?: string | undefined | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined | undefined;
    onCopy?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onCut?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onPaste?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<SVGSVGElement> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<SVGSVGElement> | undefined;
    onFocus?: import("react").FocusEventHandler<SVGSVGElement> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<SVGSVGElement> | undefined;
    onBlur?: import("react").FocusEventHandler<SVGSVGElement> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<SVGSVGElement> | undefined;
    onChange?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onChangeCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onBeforeInput?: import("react").InputEventHandler<SVGSVGElement> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onInput?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onInputCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onReset?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onResetCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onSubmit?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onInvalid?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<SVGSVGElement> | undefined;
    onLoad?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onError?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<SVGSVGElement> | undefined;
    onAbort?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onCanPlay?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onDurationChange?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEmptied?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEncrypted?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEnded?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadedData?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadStart?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPause?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPlay?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPlaying?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onProgress?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onRateChange?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSeeked?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSeeking?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onStalled?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSuspend?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onWaiting?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onAuxClick?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onClick?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onClickCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onContextMenu?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onDrag?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragEnd?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragEnter?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragExit?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragLeave?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragOver?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragStart?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDrop?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onDropCapture?: import("react").DragEventHandler<SVGSVGElement> | undefined;
    onMouseDown?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseMove?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseOut?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseOver?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseUp?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<SVGSVGElement> | undefined;
    onSelect?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<SVGSVGElement> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchMove?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchStart?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<SVGSVGElement> | undefined;
    onPointerDown?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerMove?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerUp?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerOver?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerOut?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<SVGSVGElement> | undefined;
    onScroll?: import("react").UIEventHandler<SVGSVGElement> | undefined;
    onScrollCapture?: import("react").UIEventHandler<SVGSVGElement> | undefined;
    onWheel?: import("react").WheelEventHandler<SVGSVGElement> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<SVGSVGElement> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<SVGSVGElement> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<SVGSVGElement> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<SVGSVGElement> | undefined;
}>;
