export const HOME_FETCH_POOLS_BEGIN = 'HOME_FETCH_POOLS_BEGIN';
export const HOME_FETCH_POOLS_SUCCESS = 'HOME_FETCH_POOLS_SUCCESS';
export const HOME_FETCH_POOLS_SUCCESS_WDATA = 'HOME_FETCH_POOLS_SUCCESS_WDATA';
export const WALLET_RPC_BEGIN = 'WALLET_RPC_BEGIN';
export const WALLET_RPC_SUCCESS = 'WALLET_RPC_SUCCESS';
