import type { VaultEntity } from '../../features/data/entities/vault.ts';

// Hand-curated EOL vaults to hide from v2v options
export const V2V_VAULT_BLACKLIST: ReadonlySet<VaultEntity['id']> = new Set([
  // arbitrum
  'aura-arb-gho-usdc-usdt',
  'balancer-arb-usdc-gusdc',
  'aura-arb-frax-sfrax',
  'aura-arb-susde-sfrax',
  'balancer-sfrax-4pool',
  'aura-bbaaUSD',
  'aura-bbaaUSD-v2',
  'balancer-reth-bbaweth',
  'balancer-wsteth-bbaaweth',
  'aura-reth-bbaweth-v2',
  'aura-wsteth-bbaweth-v2',
  'aura-arb-wsteth-sfrxeth',
  'aura-arb-wsteth-sfrxeth-reth',
  'aura-arb-ezeth-wsteth',
  'aura-cbeth-wsteth-reth',
  'aura-arb-cbeth-wsteth-reth-v2',
  'aura-arb-rseth-weth',
  'aura-arb-wsteth-ethx',
  'aura-wsteth-ankreth',
  'balancer-wsteth-eth',
  'balancer-wsteth-eth-v2',
  'balancer-wsteth-weth-v3',
  'balancer-weth-reth',
  'aura-arb-weth-reth-v2',
  'silov2-arbitrum-usdc-optima',
  'silov2-arbitrum-usdc-valamore',
  'balancer-tbtc-wbtc',
  'aura-dola-usdc-v2',
  'balancer-usdc-dai-usdt-usdce',
  'gmx-arb-glp',
  // avax
  'balancer-avax-savax-avax',
  'balancer-avax-usdc-eurc',
  'balancer-yyavax-bbaavavax',
  'blizz-avax-pause',
  'blizz-eth-pause',
  'blizz-wbtc-pause',
  'euler-avax-k3capital-usdt-earn',
  'silov2-avalanche-ausd-valamore',
  'silov2-avalanche-usdt-valamore',
  'silov2-avalanche-usdc-mev',
  'gmx-avax-glp',
  // base
  'balancer-base-usdbc-axlusdc',
  'balancer-base-usdc-usdbc-axlusdc',
  'balancer-base-usdbc-dai',
  'aura-base-weeth-weth',
  'balancer-base-cbeth-weth',
  'balancer-base-more-usdc',
  'balancer-base-eth-bbsusd',
  'balancer-base-weth-reth',
  // ethereum
  'aura-ankreth-wsteth',
  'aura-bbausd',
  'aura-dola-sdola',
  'aura-ethx-bbaeth',
  'aura-ezeth-eth',
  'aura-weeth-ezeth-rseth',
  'aura-gho-bbausd',
  'aura-gho-lusd',
  'aura-gho-usdc-usdt',
  'aura-pxeth-weth',
  'aura-r-bbsdai',
  'aura-r-dai',
  'aura-reth-weth',
  'aura-rseth-weth',
  'aura-sdai-3pool',
  'aura-shezeth-wsteth',
  'aura-shezusd-sdai',
  'aura-susde-usdc',
  'aura-wbeth-wsteth',
  'aura-weeth-reth',
  'aura-wsteth-reth-sfrxeth',
  'aura-wsteth-reth-sfrxeth-v2',
  'aura-wsteth-reth-sfrxeth-v3',
  'conic-crvusd-eol',
  'curve-shezeth-eth',
  'curve-shezusd-usdc',
  // sonic
  'beets-sonic-echoes-of-ether',
  'beets-sonic-ringing-stable-beets',
  'beets-sonic-staked-sonic-symphony',
  // optimism
  'aura--op-dola-usdce',
  'aura-op-ethereum-triplets',
  'aura-op-fraximalist-ethereum',
  'aura-op-reth-ankreth',
  'aura-op-usdc-usdce-usdt-dai',
  'aura-op-weth-wrseth',
  'aura-op-wsteth-weeth',
  'beets-rocket-fuel',
  'beets-shanghai-shakedown',
  'beets-yellow-submarine',
  'sonne-op-lusd',
  'sonne-op-susd',
  'sonne-op-usdt',
  'sonne-op-weth',
  // polygon
  'aura-polygon-wmatic-maticx',
  'balancer-matic-maticx-v2',
  'balancer-2brl-bbamusd',
  'balancer-brz-jbrl',
  'balancer-maticx-bbawmatic',
  'balancer-bbamUSD',
  'balancer-frxeth-bbaweth',
  'balancer-jeur-par',
  'balancer-stmatic-bbawmatic',
  'balancer-matic-stmatic-v2',
  'balancer-polygon-usdc-dai-usdt',
  'balancer-poly-wsteth-eth',
  'balancer-wsteth-bbaweth',
  'kyber-usdc-jgbp-eol',
  'kyber-usdc-jchf-eol',
  'balancer-jeur-par-v2',
]);

export function isVaultBlacklistedForV2V(vaultId: VaultEntity['id']): boolean {
  return V2V_VAULT_BLACKLIST.has(vaultId);
}
