// Generates .design-sync/entry.ts (the bundle's barrel) and the
// componentSrcMap in .design-sync/config.json.
//
// beefy-v2 is an app, not a component library: there is no published entry and
// most of src/components is wired to Redux / react-router / i18n. This picks
// the presentational subset — every .tsx under src/components whose transitive
// relative imports touch none of those — then drops the internals and app
// chrome listed in EXCLUDE.
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';

const ROOT = 'src/components';
const APP = /useAppSelector|useAppDispatch|react-i18next|react-router|features\/data\/store/;

// Internal sub-parts with generic names, app chrome, non-components, and the
// three that pull assets esbuild has no loader for (.gif / .riv).
const EXCLUDE = new Set([
  'AnimatedButton', 'AssetArrangement', 'BusdBanner', 'ClmBanner', 'Content', 'CowAnimationProvider',
  'DefaultFallback', 'DetailsDesktop', 'DevDefaultFallback', 'DropdownInner', 'DropdownOuter',
  'Footer', 'FullscreenTechLoader', 'HorizontalLayout', 'Item', 'Layout', 'Main', 'Message',
  'MessageHighlight', 'MinimalFallback', 'MissingAssetsImage', 'NotificationRpcChains', 'Option',
  'OptionBadge', 'OptionButton', 'OptionIcon', 'OptionLabel', 'RightArrow', 'SelectArrow',
  'SelectLabel', 'SelectLabelPrefix', 'Selected', 'SortIcon', 'TechLoader', 'Title',
  'VerticalLayout', 'XAxisTick',
]);

const walk = (d, out = []) => {
  for (const e of readdirSync(d)) {
    const p = join(d, e);
    statSync(p).isDirectory() ? walk(p, out) : /\.tsx?$/.test(p) && out.push(p);
  }
  return out;
};
const read = p => { try { return readFileSync(p, 'utf8'); } catch { return ''; } };
const resolveLocal = (from, spec) => {
  if (!spec.startsWith('.')) return null;
  const base = resolve(dirname(from), spec);
  const candidates = [base, base.replace(/\.tsx?$/, '.ts'), base.replace(/\.tsx?$/, '.tsx'),
    `${base}.ts`, `${base}.tsx`, join(base, 'index.ts'), join(base, 'index.tsx')];
  return candidates.find(c => existsSync(c) && statSync(c).isFile()) ?? null;
};

const memo = new Map();
const coupled = (file, stack = new Set()) => {
  if (memo.has(file)) return memo.get(file);
  if (stack.has(file)) return false;  // cycle — the other frame decides
  stack.add(file);
  const src = read(file);
  let bad = APP.test(src);
  if (!bad) {
    for (const m of src.matchAll(/from\s+['"]([^'"]+)['"]/g)) {
      const t = resolveLocal(file, m[1]);
      if (t && coupled(t, stack)) { bad = true; break; }
    }
  }
  stack.delete(file);
  memo.set(file, bad);
  return bad;
};

const found = [];
for (const f of walk(ROOT)) {
  if (!f.endsWith('.tsx') || coupled(f)) continue;
  for (const m of read(f).matchAll(/export\s+(?:const|function)\s+([A-Z][A-Za-z0-9]*)/g)) {
    found.push({ name: m[1], path: f });
  }
}

// Same name from two files → prefer the one whose own directory is the component.
const byName = new Map();
for (const c of found) {
  const score = p => (p.toLowerCase().includes(`/${c.name.toLowerCase()}/`) ? 1 : 0);
  const prev = byName.get(c.name);
  if (!prev || score(c.path) > score(prev.path)) byName.set(c.name, c);
}

const keep = [...byName.values()].filter(c => !EXCLUDE.has(c.name)).sort((a, b) => a.name.localeCompare(b.name));
const byPath = new Map();
for (const c of keep) {
  if (!byPath.has(c.path)) byPath.set(c.path, []);
  byPath.get(c.path).push(c.name);
}

const lines = [...byPath.entries()].sort()
  .map(([p, names]) => `export { ${names.sort().join(', ')} } from '../${p}';`);
writeFileSync('.design-sync/entry.ts',
  '// generated by .design-sync/gen-entry.mjs — do not edit\n' + lines.join('\n') + '\n');

const cfg = JSON.parse(readFileSync('.design-sync/config.json', 'utf8'));
cfg.componentSrcMap = Object.fromEntries(
  [...keep.map(c => [c.name, c.path]), ...[...EXCLUDE].map(n => [n, null])].sort()
);
writeFileSync('.design-sync/config.json', JSON.stringify(cfg, null, 2) + '\n');

console.log(`${lines.length} modules, ${keep.length} components, ${EXCLUDE.size} excluded`);
