const background = [
  'Multichain',
  'Moon',
  'Pastures',
  'Psychedelic',
  'Snow',
  'Beach',
  'Ethereum',
  'Moonriver',
  'Celo',
  'BSC',
  'Fantom',
  'Polygon',
  'Arbitrum',
  'Avalanche',
  'Harmony',
  'Heco',
  'Yellow',
  'Purple',
  'Red',
  'Blue',
  'Green',
  'None',
];

const body = [
  'BDSM',
  'Farmer',
  'Armored cow',
  'Cyborg skin',
  'Black suit',
  'Alien',
  'Zombie',
  'Ziggy',
  'Chicken suit',
  'Hawai shirt',
  'Cowboy suit',
  'Blue jacket',
  'Ethereum',
  'Polygon',
  'Fantom',
  'BSC',
  'Moonriver',
  'Celo',
  'Avalanche',
  'Arbitrum',
  'Harmony',
  'Heco',
  'Blue sweater',
  'Default Base',
];

const eyes = ['Pleading eyes', 'Anime eyes', 'Tired eyes', 'Normal eyes'];

const accsFace = [
  'Rayban sunglasses gold',
  'Laser eyes gold',
  'Cuban cigar gold',
  'Spliff gold',
  'Laser eyes',
  'Left ear two rings gold',
  'Monocle gold',
  'Rayban sunglasses',
  'Cuban cigar',
  'Pirate eye patch gold',
  'Spliff',
  'Aviator sunglasses gold',
  'Earrings each ear gold',
  'Left ear two rings',
  'Monocle',
  'Pirate eye patch',
  'Pipe gold',
  'Aviator blue sunglasses',
  'Left ear one ring gold',
  'Earrings each ear',
  'Multichain earring gold',
  'Pipe',
  'Left ear one ring',
  'Multichain earring',
  'None',
];

const accsBody = [
  'BIFI maxi necklace gold',
  'SAFU necklace gold',
  'BIFI maxi necklace',
  'SAFU necklace',
  "'This is fine' necklace gold",
  'Presidential sash gold',
  'Vault key gold',
  'Presidential sash',
  "'This is fine' necklace",
  'Moo necklace gold',
  'Farmer pitchfork gold',
  'Vault key',
  'Moo necklace',
  'Farmer pitchfork',
  'None',
];

const hair = ['Mohawk hair', 'Rasta hair', 'Short hair', 'Cow wig', 'Mr. T hair', 'None'];

const hat = [
  'Ethereum rainbow golden hat',
  'Top hat golden',
  'Cowboy golden hat',
  'Straw golden hat',
  'Celo golden hat',
  'Moonriver golden hat',
  'BSC golden hat',
  'Polygon golden hat',
  'Ethereum golden hat',
  'Harmony golden hat',
  'Arbitrum golden hat',
  'Fantom golden hat',
  'Avalanche golden hat',
  'Heco golden hat',
  'Straw hat',
  'Cowboy hat',
  'Top hat',
  'Celo hat',
  'Moonriver hat',
  'Ethereum rainbow hat',
  'Fantom hat',
  'Ethereum hat ',
  'BSC hat',
  'Avalanche hat',
  'Polygon hat',
  'Arbitrum hat',
  'Harmony hat',
  'Heco hat',
  'None',
];

export { background, body, eyes, accsFace, accsBody, hair, hat };
