export const styles = theme => ({
  center: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatars: {
    minHeight: '100vh',
    position: 'relative',
    backgroundColor: theme.palette.background.dark,
    backgroundImage: props => `url(${props.bgImage})`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'bottom',
    backgroundSize: '100%',
    paddingBottom: '200px',
    opacity: 1,
  },
  card: {
    background: '#14182B',
    borderRadius: '16px',
    color: theme.palette.background.cta,
    width: '168px',
    height: '168px',
    maxWidth: '80%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `2px solid ${theme.palette.background.cta}`,
    boxShadow: '-10px 10px 10px 0px #00000080',
  },
  title: {
    color: theme.palette.background.cta,
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '16px',
    textTransform: 'uppercase',
  },
  title2: {
    color: theme.palette.background.cta,
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '24px',
    textTransform: 'uppercase',
  },
  text: {
    color: theme.palette.background.muted,
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.5px',
  },
  bold: {
    color: '#FFF',
    fontWeight: 700,
    fontStyle: 'bold',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  buttons: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  btnMint: {
    backgroundColor: theme.palette.background.cta,
    fontWeight: 'bold',
    fontStyle: 'bold',
    fontSize: '16px',
    lineHeight: '24px',
    padding: '8px 24px',
    borderRadius: '8px',
  },
  btnMore: {
    marginRight: theme.spacing(2),
    backgroundColor: 'transparent',
    borderRadius: '8px',
    border: `1px solid ${theme.palette.background.cta}`,
    fontWeight: 'bold',
    fontStyle: 'bold',
    fontSize: '16px',
    lineHeight: '24px',
    padding: '8px 24px',
  },
  traitTitle: {
    color: theme.palette.background.cta,
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  traitText: {
    color: theme.palette.background.muted,
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.5px',
    '& span': {
      color: theme.palette.background.cta,
    },
  },
  divider: {
    '&.MuiDivider-vertical': {
      width: '2px',
      backgroundColor: '#3F466D',
    },
  },
});
