export const pools = {
    "bifi-maxi" : {
        id: 'bifi-maxi',
        logo: 'bifi/BIFI.png',
        name: 'HECO BIFI Maxi',
        token: 'BIFI',
        tokenDescription: 'Uses: Beefy.Finance',
        tokenAddress: '0xCa3F508B8e4Dd382eE878A314789373D80A5190A',
        tokenDecimals: 18,
        tokenDescriptionUrl: 'https://docs.beefy.finance/beefyfinance/products/bifi-maxi',
        earnedToken: 'mooBIFI',
        earnedTokenAddress: '0xf7069e41C57EcC5F122093811d8c75bdB5f7c14e',
        earnContractAddress: '0xf7069e41C57EcC5F122093811d8c75bdB5f7c14e',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'pancake',
        oracleId: 'BIFI',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'Beefy',
        assets: ['BIFI'],
        callFee: 0.5,
    },

    "auto-cake" : {
        id: 'auto-cake',
        logo: 'cake/SMART.png',
        name: 'HECO CAKE',
        token: 'CAKE',
        tokenDescription: 'Uses: Pancake',
        tokenAddress: '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooAutoCakeFixed',
        earnedTokenAddress: '0xe0B473c0dD6D7Fea5B395c3Ce7ffd4FEF0ab4373',
        earnContractAddress: '0xe0B473c0dD6D7Fea5B395c3Ce7ffd4FEF0ab4373',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'pancake',
        oracleId: 'Cake',
        oraclePrice: 0,
        depositsPaused: true,
        status: 'active',
        platform: 'Auto',
        assets: ['CAKE'],
        callFee: 0.5,
    }
}