export const styles = theme => ({
  modal: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& .MuiBackdrop-root': {
      backgroundColor: 'rgba(0,0,0,0.9)',
    },
    '& .MuiTypography-h2': {
      fontSize: '30px',
      fontWeight: 600,
      lineHeight: '42px',
      textAlign: 'center',
    },
    '& .MuiTypography-body2': {
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '20px',
      letterSpacing: '0.2px',
      paddingTop: '20px',
      textAlign: 'center',
    },
    '& .MuiAlert-root': {
      marginTop: '20px',
    },
  },
  finishedCard: {
    backgroundColor: '#323857',
    borderRadius: '20px',
    '& .MuiTypography-h2': {
      fontSize: '36px',
      lineHeight: '42px',
      fontWeight: 600,
    },
    '& .MuiTypography-body1': {
      fontSize: '14px',
      lineHeight: '20px',
      letterSpacing: '0.2px',
      textAlign: 'center',
      padding: '20px 0',
    },
  },
  finishedBtn: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#6B7199',
    backgroundColor: '#232841',
    borderRadius: '20px',
    textTransform: 'inherit',
    padding: '4px 15px',
    transition: 'color 0.2s',
    '&:hover': {
      color: '#ffffff',
      transition: 'color 0.2s',
    },
  },
  snackbar: {
    width: '350px',
    maxWidth: 'calc(min(100%, 350px) - 16px)',
    maxHeight: 'calc(100% - 16px)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'column',
  },
  snackbarContainer: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  topBar: {
    height: '10px',
    borderRadius: '4px 4px 0 0',
    backgroundColor: theme.palette.background.snackbars.bgLine,
    flexShrink: 0,
    flexGrow: 0,
  },
  progressBar: {
    width: '50%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  progressBar25: {
    width: '25%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  progressBar50: {
    width: '50%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  progressBar75: {
    width: '75%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  progressBar1: {
    width: '75%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  confirmationBar: {
    width: '75%',
    margin: 0,
    backgroundColor: theme.palette.primary.main,
    height: '100%',
    borderRadius: '4px 0 0 0',
  },
  successBar: {
    width: '100%',
    margin: 0,
    height: '100%',
    backgroundColor: theme.palette.primary.main,
    borderRadius: '4px 4px 0 0',
  },
  errorBar: {
    width: '100%',
    margin: 0,
    height: '100%',
    backgroundColor: theme.palette.background.snackbars.error,
    borderRadius: '4px 4px 0 0',
  },
  icon: {
    height: '20px',
    marginRight: theme.spacing(1),
  },
  titleContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexShrink: 0,
  },
  closeIcon: {
    padding: 0,
  },
  contentContainer: {
    backgroundColor: theme.palette.background.snackbars.bg,
    borderRadius: '0 0 4px 4px',
    padding: '12px 16px',
    minHeight: 0,
    flexShrink: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'auto',
  },
  title: {
    color: theme.palette.background.snackbars.text,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
  },
  friendlyMessage: {
    fontWeight: 700,
    color: theme.palette.background.snackbars.text,
    marginBottom: theme.spacing(2),
  },
  message: {
    color: theme.palette.background.snackbars.text,
    '& span': {
      fontWeight: 700,
    },
  },
  content: {
    marginTop: theme.spacing(1.5),
    padding: '16px',
    borderRadius: '4px',
  },
  errorContent: {
    backgroundColor: 'rgba(219, 50, 50, 0.1)',
  },
  successContent: {
    backgroundColor: 'rgba(89, 166, 98, 0.15)',
  },
  closeBtn: {
    marginTop: theme.spacing(3),
    backgroundColor: theme.palette.background.snackbars.bgBtn,
    color: theme.palette.text.primary,
    width: '100%',
    fontSize: '15px',
    lineHeight: '24px',
    fontWeight: 700,
    borderRadius: '8px',
    textTransform: 'none',
    '&:Hover': {
      backgroundColor: theme.palette.background.snackbars.bgBtn,
    },
  },
  redirectBtnSuccess: {
    color: theme.palette.primary.main,
    background: 'none',
    textTransform: 'none',
    margin: 0,
    padding: 0,
    '& .MuiSvgIcon-root': {
      height: '15px',
    },
  },
});
