import { css } from '@repo/styles/css';

export const styles = {
  container: css.raw({
    display: 'flex',
    alignItems: 'center',
    padding: '0px 8px',
    gap: '8px',
    color: 'text.middle',
    '&:hover': {
      cursor: 'pointer',
      color: 'text.light',
    },
  }),
  dropdown: css.raw({
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'background.content',
    border: `solid 2px {colors.background.content.dark}`,
    borderRadius: '8px',
    marginTop: '4px',
    width: '280px',
    zIndex: 999,
  }),
  header: css.raw({
    textStyle: 'body.med',
    color: 'text.light',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${12 - 2}px`,
    backgroundColor: 'background.content.dark',
    borderRadius: '8px 8px 0px 0px',
  }),
  title: css.raw({
    display: 'flex',
    alignItems: 'center',
    '& img': {
      height: '24px',
      margin: '0px 4px',
    },
  }),
  cross: css.raw({
    color: 'text.dark',
    '&:hover': {
      color: 'text.light',
      cursor: 'pointer',
    },
  }),
  content: css.raw({
    height: '356px',
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
  }),
  list: css.raw({
    padding: `${12 - 2}px`,
    height: '100%',
    width: '100%',
    color: 'text.light',
    flexGrow: '1',
  }),
  footer: css.raw({
    display: 'flex',
    justifyContent: 'center',
    marginTop: '24px',
    padding: `${12 - 2}px`,
    borderRadius: '0 0 8px 8px',
  }),
  edit: css.raw({
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: `${12 - 2}px`,
    rowGap: '16px',
    color: 'text.middle',
    flexGrow: '1',
  }),
  chainInfo: css.raw({
    textStyle: 'body.med',
    display: 'flex',
    columnGap: '8px',
    color: 'text.middle',
  }),
  input: css.raw({
    color: 'text.dark',
    background: 'purpleDarkest',
    borderRadius: '8px',
    '& .MuiInputBase-input': {
      padding: '8px 16px',
      color: 'text.dark',
      height: 'auto',
      '&:focus': {
        color: 'text.light',
      },
      '&::placeholder': {
        color: 'text.dark',
        opacity: 1,
      },
    },
  }),
  listItemIcon: css.raw({
    marginRight: '8px',
  }),
  modifiedListItem: css.raw({
    textStyle: 'body.med',
    display: 'flex',
    gap: '8px',
    color: 'text.middle',
  }),
  url: css.raw({
    textStyle: 'body.sm',
    marginLeft: '32px',
    color: 'text.dark',
    width: '196px',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textAlign: 'start',
  }),
  emptyTextContainer: css.raw({
    textStyle: 'body.sm.med',
    padding: '12px',
    backgroundColor: 'background.content.light',
    borderRadius: '8px',
    color: 'text.middle',
  }),
  emptyIcon: css.raw({
    height: '120px',
    width: '120px',
  }),
  backIcon: css.raw({
    fill: 'text.light',
    width: '12px',
    height: '9px',
  }),
  backButton: css.raw({
    margin: 0,
    padding: 0,
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    background: 'bayOfMany',
    boxShadow: 'none',
    cursor: 'pointer',
    border: 'none',
    color: 'text.light',
    flexShrink: 0,
    flexGrow: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  headerTitle: css.raw({
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  }),
  line: css.raw({
    height: '16px',
    width: '2px',
    borderRadius: '3px',
    backgroundColor: 'background.content.dark',
  }),
  inputContainer: css.raw({
    display: 'flex',
    flexDirection: 'column',
  }),
  inputError: css.raw({
    textStyle: 'body.sm',
    color: 'indicators.error',
    marginLeft: '16px',
    transition: 'ease-in-out 2s;',
  }),
};
