export const pools = [
    {
        id: 'froyo-3pool',
        logo: 'fantom/FROYO-3Pool.png',
        name: 'USDT/DAI/USDC',
        token: 'FROYO 3Pool',
        tokenDescription: 'Froyo',
        tokenAddress: '0x4f85Bbf3B0265DCEd4Ec72ebD0358ccCf190F1B3',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooFroyo3Pool',
        earnedTokenAddress: '0xb18398ad9735fea37C97dcba50C0Bb947Dc0eeBD',
        earnContractAddress: '0xb18398ad9735fea37C97dcba50C0Bb947Dc0eeBD',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'froyo-3pool',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'Froyo',
        assets: ['USDT', 'DAI', 'USDC'],
        callFee: 0.5,
        addLiquidityUrl: 'https://frozenyogurt.finance/pool',
        network: 'fantom'
    },
    {
        id: 'froyo-froyo-ftm',
        logo: 'fantom/FROYO.png',
        name: 'FROYO-FTM LP',
        token: 'FROYO-FTM LP',
        tokenDescription: 'SushiSwap',
        tokenAddress: '0xBE0AF661BC9794E05fAb18C08C2C99811A0F45D2',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooFroyoFROYO-FTM',
        earnedTokenAddress: '0xeD4ea30c755676C07d3e0e0f74Ff84C0193B4551',
        earnContractAddress: '0xeD4ea30c755676C07d3e0e0f74Ff84C0193B4551',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'froyo-froyo-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'Froyo',
        assets: ['FROYO', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://app.sushi.com/add/ETH/0xA92d41Ab8eFeE617d80a829CD9F5683c5F793ADA',
        buyTokenUrl:
            'https://app.sushi.com/swap?outputCurrency=0xA92d41Ab8eFeE617d80a829CD9F5683c5F793ADA',
        network: 'fantom'
        },
    {
        id: 'boo-link-ftm',
        logo: 'fantom/LINK-FTM.png',
        name: 'LINK-FTM LP',
        token: 'LINK-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0x89d9bc2f2d091cfbfc31e333d6dc555ddbc2fd29',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooLINK-FTM',
        earnedTokenAddress: '0x711969A90C9EDD815A5C2b441FC80d067EC5E969',
        earnContractAddress: '0x711969A90C9EDD815A5C2b441FC80d067EC5E969',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-link-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['LINK', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-cover-ftm',
        logo: 'fantom/COVER-FTM.png',
        name: 'COVER-FTM LP',
        token: 'COVER-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0x5DC7848bF215F1D99F2AF3d2Bf78fcdf238EE34b',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooCOVER-FTM',
        earnedTokenAddress: '0xF5Bf6b3624eb10Ee855FEC1C5a4af81D90996b6c',
        earnContractAddress: '0xF5Bf6b3624eb10Ee855FEC1C5a4af81D90996b6c',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-cover-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['COVER', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-cream-ftm',
        logo: 'fantom/CREAM-FTM.png',
        name: 'CREAM-FTM LP',
        token: 'CREAM-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xb77b223490e1f5951ec79A8d09Db9Eab2ADCB934',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooCREAM-FTM',
        earnedTokenAddress: '0x2BDA70d1DcE6b0855e812daaBB096F3DaaEBd4Bc',
        earnContractAddress: '0x2BDA70d1DcE6b0855e812daaBB096F3DaaEBd4Bc',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-cream-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['CREAM', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-snx-ftm',
        logo: 'fantom/SNX-FTM.png',
        name: 'SNX-FTM LP',
        token: 'SNX-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0x06d173628bE105fE81F1C82c9979bA79eBCAfCB7',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooSNX-FTM',
        earnedTokenAddress: '0x74907ad4E79b1Ce415caB26FEf526ae017598cEe',
        earnContractAddress: '0x74907ad4E79b1Ce415caB26FEf526ae017598cEe',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-snx-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['SNX', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-yfi-ftm',
        logo: 'fantom/YFI-FTM.png',
        name: 'YFI-FTM LP',
        token: 'YFI-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xBf4d61d4cec3a9DFf7452D8987E1Cc2943e2EB4C',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooYFI-FTM',
        earnedTokenAddress: '0x2dC73D17Ae01De6D49aab45668601591FF283dee',
        earnContractAddress: '0x2dC73D17Ae01De6D49aab45668601591FF283dee',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-yfi-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['YFI', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-usdt-ftm',
        logo: 'fantom/USDT-FTM.png',
        name: 'fUSDT-FTM LP',
        token: 'fUSDT-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0x5965E53aa80a0bcF1CD6dbDd72e6A9b2AA047410',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooUSDT-FTM',
        earnedTokenAddress: '0x5d89017d2465115007AbA00da1E6446dF2C19f34',
        earnContractAddress: '0x5d89017d2465115007AbA00da1E6446dF2C19f34',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-usdt-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['fUSDT', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-btc-ftm',
        logo: 'fantom/BTC-FTM.png',
        name: 'BTC-FTM LP',
        token: 'BTC-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xFdb9Ab8B9513Ad9E419Cf19530feE49d412C3Ee3',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooBTC-FTM',
        earnedTokenAddress: '0xA3e3Af161943CfB3941B631676134bb048739727',
        earnContractAddress: '0xA3e3Af161943CfB3941B631676134bb048739727',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-btc-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['BTC', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-eth-ftm',
        logo: 'fantom/ETH-FTM.png',
        name: 'ETH-FTM LP',
        token: 'ETH-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xf0702249F4D3A25cD3DED7859a165693685Ab577',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooETH-FTM',
        earnedTokenAddress: '0x2a30C5e0d577108F694d2A96179cd73611Ee069b',
        earnContractAddress: '0x2a30C5e0d577108F694d2A96179cd73611Ee069b',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-eth-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['ETH', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-aave-ftm',
        logo: 'fantom/AAVE-FTM.png',
        name: 'AAVE-FTM LP',
        token: 'AAVE-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xeBF374bB21D83Cf010cC7363918776aDF6FF2BF6',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooAAVE-FTM',
        earnedTokenAddress: '0xDa4bb93Bac7CC00F6c6e2193d115Cf45099b31a0',
        earnContractAddress: '0xDa4bb93Bac7CC00F6c6e2193d115Cf45099b31a0',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-aave-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['AAVE', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-crv-ftm',
        logo: 'fantom/CRV-FTM.png',
        name: 'CRV-FTM LP',
        token: 'CRV-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xB471Ac6eF617e952b84C6a9fF5de65A9da96C93B',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooCRV-FTM',
        earnedTokenAddress: '0xdf68Bf80D427A5827Ff2c06A9c70D407e17DC041',
        earnContractAddress: '0xdf68Bf80D427A5827Ff2c06A9c70D407e17DC041',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-crv-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['CRV', 'FTM'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-boo-ftm',
        logo: 'fantom/BOO-FTM.png',
        name: 'BOO-FTM LP',
        token: 'BOO-FTM LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0xEc7178F4C41f346b2721907F5cF7628E388A7a58',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooBoo-FTM',
        earnedTokenAddress: '0xEe3a7c885Fd3cc5358FF583F2DAB3b8bC473316f',
        earnContractAddress: '0xEe3a7c885Fd3cc5358FF583F2DAB3b8bC473316f',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-boo-ftm',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['FTM', 'BOO'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
        network: 'fantom'
        },
    {
        id: 'boo-ftm-usdc',
        logo: 'fantom/USDC-FTM.png',
        name: 'FTM-USDC LP',
        token: 'FTM-USDC LP',
        tokenDescription: 'SpookySwap',
        tokenAddress: '0x2b4C76d0dc16BE1C31D4C1DC53bF9B45987Fc75c',
        tokenDecimals: 18,
        tokenDescriptionUrl: '#',
        earnedToken: 'mooBooFTM-USDC',
        earnedTokenAddress: '0x41D44B276904561Ac51855159516FD4cB2c90968',
        earnContractAddress: '0x41D44B276904561Ac51855159516FD4cB2c90968',
        pricePerFullShare: 1,
        tvl: 0,
        oracle: 'lps',
        oracleId: 'boo-ftm-usdc',
        oraclePrice: 0,
        depositsPaused: false,
        status: 'active',
        platform: 'SpookySwap',
        assets: ['FTM', 'USDC'],
        callFee: 0.5,
        addLiquidityUrl:
            'https://spookyswap.finance/add',
        buyTokenUrl:
            'https://spookyswap.finance/swap',
    },
];