import { StrategyConfig } from './types';

export default {
  tokenProviderId: async (chainId, strategyAddress, vaultReceiptName) => {
    if (chainId === 'base') {
      return 'aerodrome';
    }
    return 'velodrome';
  },
  abi: [
    {
      inputs: [],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
      name: 'AddressEmptyCode',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'AddressInsufficientBalance',
      type: 'error',
    },
    { inputs: [], name: 'FailedInnerCall', type: 'error' },
    {
      inputs: [],
      name: 'InvalidEntry',
      type: 'error',
    },
    { inputs: [], name: 'InvalidInput', type: 'error' },
    {
      inputs: [],
      name: 'InvalidOutput',
      type: 'error',
    },
    { inputs: [], name: 'NotAuthorized', type: 'error' },
    {
      inputs: [],
      name: 'NotCalm',
      type: 'error',
    },
    { inputs: [], name: 'NotManager', type: 'error' },
    {
      inputs: [],
      name: 'NotPool',
      type: 'error',
    },
    { inputs: [], name: 'NotStrategist', type: 'error' },
    {
      inputs: [],
      name: 'NotVault',
      type: 'error',
    },
    { inputs: [], name: 'OverLimit', type: 'error' },
    {
      inputs: [
        {
          internalType: 'address',
          name: 'token',
          type: 'address',
        },
      ],
      name: 'SafeERC20FailedOperation',
      type: 'error',
    },
    { inputs: [], name: 'StrategyPaused', type: 'error' },
    {
      inputs: [],
      name: 'TooMuchSlippage',
      type: 'error',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint256',
          name: 'callFeeAmount',
          type: 'uint256',
        },
        { indexed: false, internalType: 'uint256', name: 'beefyFeeAmount', type: 'uint256' },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'strategistFeeAmount',
          type: 'uint256',
        },
      ],
      name: 'ChargedFees',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'fees', type: 'uint256' }],
      name: 'ClaimedRewards',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'fees', type: 'uint256' }],
      name: 'HarvestRewards',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
      name: 'Initialized',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'previousOwner',
          type: 'address',
        },
        { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
      name: 'Paused',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'int56', name: 'maxTickDeviation', type: 'int56' }],
      name: 'SetDeviation',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'bytes', name: 'path', type: 'bytes' }],
      name: 'SetOutputToNativePath',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'int24', name: 'oldWidth', type: 'int24' },
        {
          indexed: false,
          internalType: 'int24',
          name: 'width',
          type: 'int24',
        },
      ],
      name: 'SetPositionWidth',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'rewardPool', type: 'address' }],
      name: 'SetRewardPool',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint256', name: 'feeId', type: 'uint256' }],
      name: 'SetStratFeeId',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'strategist', type: 'address' }],
      name: 'SetStrategist',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint32',
          name: 'oldInterval',
          type: 'uint32',
        },
        { indexed: false, internalType: 'uint32', name: 'interval', type: 'uint32' },
      ],
      name: 'SetTwapInterval',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'unirouter', type: 'address' }],
      name: 'SetUnirouter',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, internalType: 'uint256', name: 'bal0', type: 'uint256' },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'bal1',
          type: 'uint256',
        },
      ],
      name: 'TVL',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
      name: 'Unpaused',
      type: 'event',
    },
    {
      inputs: [],
      name: 'balances',
      outputs: [
        { internalType: 'uint256', name: 'token0Bal', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'token1Bal',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'balancesOfPool',
      outputs: [
        { internalType: 'uint256', name: 'token0Bal', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'token1Bal',
          type: 'uint256',
        },
        { internalType: 'uint256', name: 'mainAmount0', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'mainAmount1',
          type: 'uint256',
        },
        { internalType: 'uint256', name: 'altAmount0', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'altAmount1',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'balancesOfThis',
      outputs: [
        { internalType: 'uint256', name: 'token0Bal', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'token1Bal',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'beefyFeeConfig',
      outputs: [{ internalType: 'contract IFeeConfig', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'beefyFeeRecipient',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'beforeAction',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'currentTick',
      outputs: [{ internalType: 'int24', name: 'tick', type: 'int24' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'deposit',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'depositFee',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'factory',
      outputs: [{ internalType: 'contract IStrategyFactory', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'fees',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'gauge',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getAllFees',
      outputs: [
        {
          components: [
            {
              components: [
                {
                  internalType: 'uint256',
                  name: 'total',
                  type: 'uint256',
                },
                { internalType: 'uint256', name: 'beefy', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'call',
                  type: 'uint256',
                },
                { internalType: 'uint256', name: 'strategist', type: 'uint256' },
                {
                  internalType: 'string',
                  name: 'label',
                  type: 'string',
                },
                { internalType: 'bool', name: 'active', type: 'bool' },
              ],
              internalType: 'struct IFeeConfig.FeeCategory',
              name: 'performance',
              type: 'tuple',
            },
            { internalType: 'uint256', name: 'deposit', type: 'uint256' },
            {
              internalType: 'uint256',
              name: 'withdraw',
              type: 'uint256',
            },
          ],
          internalType: 'struct IFeeConfig.AllFees',
          name: '',
          type: 'tuple',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getStratFeeId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_callFeeRecipient', type: 'address' }],
      name: 'harvest',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'harvest',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_pool', type: 'address' },
        {
          internalType: 'address',
          name: '_quoter',
          type: 'address',
        },
        { internalType: 'address', name: '_nftManager', type: 'address' },
        {
          internalType: 'address',
          name: '_gauge',
          type: 'address',
        },
        { internalType: 'address', name: '_rewardPool', type: 'address' },
        {
          internalType: 'address',
          name: '_output',
          type: 'address',
        },
        { internalType: 'int24', name: '_positionWidth', type: 'int24' },
        {
          internalType: 'bytes[]',
          name: '_paths',
          type: 'bytes[]',
        },
        {
          components: [
            { internalType: 'address', name: 'vault', type: 'address' },
            {
              internalType: 'address',
              name: 'unirouter',
              type: 'address',
            },
            { internalType: 'address', name: 'strategist', type: 'address' },
            {
              internalType: 'address',
              name: 'factory',
              type: 'address',
            },
          ],
          internalType: 'struct StratFeeManagerInitializable.CommonAddresses',
          name: '_commonAddresses',
          type: 'tuple',
        },
      ],
      name: 'initialize',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'isCalm',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'keeper',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lastHarvest',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lastPositionAdjustment',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lockedProfit',
      outputs: [
        { internalType: 'uint256', name: 'locked0', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'locked1',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken0',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken0ToNativePath',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken0ToNativePrice',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken1',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken1ToNativePath',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'lpToken1ToNativePrice',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'maxTickDeviation',
      outputs: [{ internalType: 'int56', name: '', type: 'int56' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'moveTicks',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'native',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'nftManager',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        {
          internalType: 'address',
          name: '',
          type: 'address',
        },
        { internalType: 'uint256', name: '', type: 'uint256' },
        {
          internalType: 'bytes',
          name: '',
          type: 'bytes',
        },
      ],
      name: 'onERC721Received',
      outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [],
      name: 'output',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'outputToNativePath',
      outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'outputToNativePrice',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_minAmount0', type: 'uint256' },
        {
          internalType: 'uint256',
          name: '_minAmount1',
          type: 'uint256',
        },
      ],
      name: 'panic',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'paused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'pool',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'positionAlt',
      outputs: [
        { internalType: 'uint256', name: 'nftId', type: 'uint256' },
        {
          internalType: 'int24',
          name: 'tickLower',
          type: 'int24',
        },
        { internalType: 'int24', name: 'tickUpper', type: 'int24' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'positionMain',
      outputs: [
        { internalType: 'uint256', name: 'nftId', type: 'uint256' },
        {
          internalType: 'int24',
          name: 'tickLower',
          type: 'int24',
        },
        { internalType: 'int24', name: 'tickUpper', type: 'int24' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'positionWidth',
      outputs: [{ internalType: 'int24', name: '', type: 'int24' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'price',
      outputs: [{ internalType: 'uint256', name: '_price', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'quoter',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'range',
      outputs: [
        { internalType: 'uint256', name: 'lowerPrice', type: 'uint256' },
        {
          internalType: 'uint256',
          name: 'upperPrice',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'renounceOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'retireVault',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'rewardPool',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'int56', name: '_maxDeviation', type: 'int56' }],
      name: 'setDeviation',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'int24', name: '_width', type: 'int24' }],
      name: 'setPositionWidth',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_rewardPool', type: 'address' }],
      name: 'setRewardPool',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_feeId', type: 'uint256' }],
      name: 'setStratFeeId',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_strategist', type: 'address' }],
      name: 'setStrategist',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint32', name: '_interval', type: 'uint32' }],
      name: 'setTwapInterval',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_unirouter', type: 'address' }],
      name: 'setUnirouter',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'sqrtPrice',
      outputs: [{ internalType: 'uint160', name: 'sqrtPriceX96', type: 'uint160' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'strategist',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'swapFee',
      outputs: [{ internalType: 'uint256', name: 'fee', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalLocked0',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalLocked1',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'twap',
      outputs: [{ internalType: 'int56', name: 'twapTick', type: 'int56' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'twapInterval',
      outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'unirouter',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'vault',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_amount0', type: 'uint256' },
        {
          internalType: 'uint256',
          name: '_amount1',
          type: 'uint256',
        },
      ],
      name: 'withdraw',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'withdrawFee',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    { stateMutability: 'payable', type: 'receive' },
  ],
} as const satisfies StrategyConfig;
