import type { ChainId } from '../../features/data/entities/chain.ts';

export const tenderlyChains = new Set<ChainId>([
  'ethereum',
  'polygon',
  'optimism',
  'arbitrum',
  'bsc',
  'base',
  'fraxtal',
  'avax',
  'linea',
  'moonbeam',
  'moonriver',
  'gnosis',
  'rootstock',
  'metis',
  'zksync',
  'sonic',
  'scroll',
  'celo',
  'plasma',
  'monad',
  'megaeth',
]);
