export const pools = [
  {
    id: 'moo_vvs-cro-btc-liquidus',
    poolId: 'vvs-cro-btc',
    name: 'Liquidus',
    assets: ['CRO', 'WBTC'],
    earnedToken: 'LIQ',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0xABd380327Fe66724FFDa91A87c772FB8D00bE488',
    earnContractAddress: '0xF424488CD9213b6Fd83F63C2BdCA8B0492b2a9a5',
    earnedOracle: 'tokens',
    earnedOracleId: 'LIQ',
    partnership: true,
    status: 'active',
    isMooStaked: true,
    partners: [
      {
        logo: 'stake/liquidus/logo.png',
        background: 'stake/liquidus/bg.png',
        text: 'Liquidus is a practical tool that will allow you to easily stake your crypto assets on leading DeFi platforms. We’ll bring the rapidly expanding Decentralized Finance (DeFi) ecosystem to the masses, breaking complicated processes down through easy-to-use, simplistic interfaces. We’re here to change how people think about DeFi and our much-anticipated web and mobile application is planned for launch in Q1 of 2022.',
        website: 'https://farm.liquidus.finance/',
        social: {
          telegram: 'https://t.me/liquidusfinance',
          twitter: 'https://twitter.com/LiquidusFinance',
        },
      },
    ],
  },
  {
    id: 'moo_vvs-vvs-cro-darkcrypto',
    poolId: 'vvs-vvs-cro',
    name: 'DarkCrypto',
    assets: ['VVS', 'CRO'],
    earnedToken: 'SKY',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x9D3BBb0e988D9Fb2d55d07Fe471Be2266AD9c81c',
    earnContractAddress: '0xE06575Cfd4a631e8C0Cd9FBDd8d77AB04CFfA52C',
    earnedOracle: 'tokens',
    earnedOracleId: 'SKY',
    partnership: true,
    status: 'active',
    isMooStaked: true,
    partners: [
      {
        logo: 'stake/dark/logo.png',
        background: 'stake/dark/bg.png',
        text: 'DarkCrypto - Algorithms Token Pegged With CRO on CRONOS chain. $DARK will be an on-demand token for DarkVerse - Universe of GameFi and metaverse.',
        website: 'https://www.darkcrypto.finance/',
        social: {
          telegram: 'https://t.me/darkcryptofi',
          twitter: 'https://twitter.com/DarkCryptoFi',
        },
      },
    ],
  },
];
